### PR TITLE
added "fromNow" functionality

### PR DESCRIPTION
**Pull request by hlandao**

### CODE REVIEW

**Comment by akosma** [comment]
Thanks for the pull request, it looks very useful. Could you please add some tests for the method you've included? I'll make sure to merge this asap but it has to have some tests.

**Comment by kevinmanncito** [comment]
Just found this library today looking for the `fromNow` method. I might have to write the tests for @hlandao...

**Comment by netgfx** [comment]
Is this feature something that will be added?

**Comment by akosma** [comment]
@netgfx I'm leaving this open until the author provides some tests for the feature.

**Comment by akosma** [comment]
This feature has been included in PR #54

**Pull request closed without merging**
