### PR TITLE
fixes #1 - use NSDateFormatter singleton

### LINKED ISSUE #1: Inefficient use of NSDateFormatter
Instantiate NSDateFormatter is expensive operation and you use it exactly that way. You can read this in [Apple documentation](https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/DataFormatting/Articles/dfDateFormatting10_4.html#//apple_ref/doc/uid/TP40002369-SW1):

> Creating a date formatter is not a cheap operation. If you are likely to use a formatter frequently, it is typically more efficient to cache a single instance than to create and dispose of multiple instances. One approach is to use a static variable.

### PR DESCRIPTION
**Pull request by xyclos**

### CODE REVIEW

**Comment by getaaron** [comment]
This approach will persist locale, timezone, and formatting changes between method calls, which is unexpected.

**Comment by getaaron** [comment]
I haven't checked, but I imagine the tests don't all pass any more.

**Comment by xyclos** [comment]
I ran the tests, they were passing except for the ones that were already not passing before the change.

edit: you may still have a point in your first comment though.

**Comment by akosma** [comment]
I understand that creating an NSDateFormatter is an expensive operation, however as @getaaron says, the formatting will be fixed after the first call, which is not what the user might expect at first. I mean, if I want a date with full month names and another without from the same moment… it will not be a nice experience.

So, I think now that a suitable solution might be the following: allow the client library to specify a "preferred format" on the Moment instance, this format is passed to a fixed NSDateFormatter instance inside of the Moment, and this is subsequently used at every format call.

Clients will still be able to use the inefficient, non-cached formatter version if they want – because, after all, they can do the same manually anyway. But in the documentation we can make clear our intentions, and that the recommended way to use the library is to pass a "preferred format" at some point before formatting dates.

Does this makes sense? Would it be useful? Thanks for your input!

**Comment by getaaron** [comment]
Another option would be to implement a method that is called before/after every use that resets it to some defaults. For example…

``` swift
func resetMomentFormatter() {
    momentFormatter.timeZone = NSTimeZone(name: "GMT")
    momentFormatter.locale = NSLocale.autoupdatingCurrentLocale()
    momentFormatter.dateFormat = ""
}
```

**Pull request closed without merging**
