### PR TITLE
Update to Swift 2.0

### PR DESCRIPTION
**Pull request by armstrongnate**
I did not do much apart from running it through the Xcode converter. The main changes are instead of using the full names for calendar components (eg `CalendarUnitYear`) we now use the enum (eg `.Year`).

### CODE REVIEW

**Comment by karupanerura** [comment]
:+1:

**Comment by karupanerura** [comment]
I think it is too early to merge, but there is a need to want to try it.
One idea, Create `swift-2.0` branch, and merge it to `swift-2.0`.
What about? @akosma

**Comment by akosma** [comment]
Hi everyone, sorry for the radio silence; I'll be checking this as soon as possible! Thanks for the support and definitely we gotta move to Swift 2.0.

**Comment by chandlervdw** [comment]
@akosma any update on moving to Swift 2.0?

**Comment by staticdreams** [comment]
Xcode 7 with Swift 2.0 is just around the corner! We need you SwiftMoment!

**Comment by vince-marco** [comment]
Xcode 7 with Swift 2.0 is here!  Any estimate on a SwiftMoment update?

**Comment by karupanerura** [comment]
@akosma Can I help you?

**Comment by akosma** [comment]
I'm going to merge #27 since it is more recent. Thanks a lot and sorry for the time it took to review!

**Pull request closed without merging**
